### ISSUE TITLE
Adding too much spaces to the @hook annotation break the filter registration

### ISSUE THREAD

**Issue by CrochetFeve0251** [CrochetFeve0251/rocket-launcher-core#39]
@nicomollet found that when using the annotation for hooks, if there was more than one space between `@hook` and the name of the hook, then it would not work.

This problem can be solved by changing the regex to match one or multiple spaces.

Acceptance criteria:
- GIVEN a hook is defined with one space before its name WHEN the hook is registered THEN this callback should be present.
- GIVEN a hook is defined with two spaces before its name WHEN the hook is registered THEN this callback should be present.
- GIVEN a hook is defined with one space before its priority WHEN the hook is registered THEN this callback should be present.
- GIVEN a hook is defined with two spaces before its priority WHEN the hook is registered THEN this callback should be present.

**Comment by nicomollet** [comment]
Current regex for the `@hook` parsing: `#@hook\s(?<name>[a-zA-Z\\\-_$/]+)(\s(?<priority>[0-9]+))?#`

Proposed change to `#@hook\s+(?<name>[a-zA-Z0-9\\\-_$/]+)(\s+(?<priority>[0-9]+))?#`:
- Allow multiple spaces between `@hook` and hook name
- Allow multiple spaces between hook name and priority
- Allow numbers in the hook name (we might need to add dates in the hook name)

[Testing the new regex online](https://onlinephp.io/preg-match-all?d=q1YqSCwpSS3KU7JSUnbIyM_Pjokp1tawt8lLzE21i07UrXLUjTLQtYwBA914lRj9WG1NDaiigqLM_KLMkkq7aKASoLimvbKSjlJxaVJWanIJ0ESwgQogo-Lz0-JBnHgDw5iimDyIBJqMEUIGVcIYhxacJpkoGBrglDRVAMoCnZmWk5heDHRkQJCre3ywa0i8f5CLaxBQIj8trTgV5HyQqjIgbaFnpGdoqVQLAA%2C%2C&v=8.2.19).
